/** Main query builder type returned by `table(...)`. */
export {
  Query,
  explain,
  fold,
  filter,
  join,
  take,
  loop,
  sort,
  map,
  t,
  table,
  toAst,
  toIR,
  toSql,
  toSqlResult,
  union,
  unionAll,
} from "./src/edsl/query.ts";
export type { QueryExplainResult, QueryIR, QueryStageKind, QueryStep } from "./src/edsl/query.ts";

/** Expression builder and helpers for composing SQL expressions. */
export {
  ExprRef,
  eq,
  ne,
  gt,
  gte,
  lt,
  lte,
  like,
  isIn,
  and,
  or,
  not,
  add,
  sub,
  mul,
  div,
  mod,
  extract,
  dateTrunc,
  dateAdd,
  dateDiff,
  dateFormat,
  dateParse,
  toUnixTime,
  fromUnixTime,
  year,
  month,
  day,
  hour,
  minute,
  second,
  group,
  count,
  sum,
  avg,
  min,
  max,
  rank,
  denseRank,
  rowNumber,
  lag,
  lead,
  percentRank,
  ntile,
  ceil,
  floor,
  abs,
  sqrt,
  pow,
  greatest,
  least,
  replace,
  upper,
  lower,
  reverse,
  trim,
  regexLike,
  regexReplace,
  regexExtract,
  substring,
  position,
  overlay,
  charLength,
  characterLength,
  octetLength,
  bitLength,
  left,
  right,
  lpad,
  rpad,
  concat,
  arrayLength,
  arrayContains,
  arrayPosition,
  arraySlice,
  arrayJoin,
  arrayAppend,
  arrayPrepend,
  arrayConcat,
  arrayDistinct,
  coalesce,
  nullIf,
  isNull,
  isNotNull,
  asc,
  desc,
  sumOver,
  cast,
  toInt,
  toFloat,
  toDate,
  round,
  array,
  fn,
  windowFn,
  over,
  caseWhen,
  when,
  mapShape,
  groupShape,
  f,
  lit,
  param,
  currentDate,
  currentTimestamp,
  dateLiteral,
  timestampLiteral,
} from "./src/edsl/expr.ts";

/** Language specification and dialect mapping helpers. */
export { LANGUAGE_SPEC, getLanguageSpec } from "./src/edsl/sql/language.ts";
export type { LanguageCategory } from "./src/edsl/sql/language.ts";
export type {
  ExprSqlTarget,
  QuerySqlTarget,
  SqlCompilable,
} from "./src/edsl/sql.ts";

/** Common SQL type aliases and SQL rendering options. */
export type {
  BuiltinDialect,
  DialectLanguageConfig,
  DialectLanguageFallback,
  DialectFeatures,
  DialectSpec,
  QueryDialect,
  SqlInt,
  SqlFloat,
  SqlBigInt,
  SqlDecimal,
  SqlNumber,
  SqlDate,
  SqlTimestamp,
  SqlUuid,
  SqlBytes,
  SqlJson,
  Dialect,
  SqlFormat,
  SqlRenderStrategy,
  SqlOptions,
  SqlParam,
  SqlParameterMode,
  SqlParameterPrefix,
  SqlResult,
  IdentifierInput,
  SqlIdentifier,
} from "./src/edsl/types.ts";

/** Public error types for distinguishing user errors from internal compiler failures. */
export {
  TetaError,
  TetaInternalError,
  TetaUserError,
  isTetaError,
} from "./src/edsl/errors.ts";
export type { TetaErrorCode, TetaErrorKind } from "./src/edsl/errors.ts";
