/** Main query builder type returned by `table(...)`. */
export { Query, table, loop, t } from "./src/edsl/query";

/** Expression builder and helpers for composing SQL expressions. */
export {
  ExprRef,
  eq,
  ne,
  gt,
  gte,
  lt,
  lte,
  like,
  isIn,
  and,
  or,
  not,
  add,
  sub,
  mul,
  div,
  mod,
  extract,
  dateTrunc,
  dateAdd,
  dateDiff,
  dateFormat,
  dateParse,
  toUnixTime,
  fromUnixTime,
  year,
  month,
  day,
  hour,
  minute,
  second,
  group,
  count,
  sum,
  avg,
  min,
  max,
  rank,
  denseRank,
  rowNumber,
  lag,
  lead,
  percentRank,
  ntile,
  ceil,
  floor,
  abs,
  sqrt,
  pow,
  greatest,
  least,
  replace,
  upper,
  lower,
  reverse,
  trim,
  regexLike,
  regexReplace,
  regexExtract,
  substring,
  position,
  overlay,
  charLength,
  characterLength,
  octetLength,
  bitLength,
  left,
  right,
  lpad,
  rpad,
  concat,
  arrayLength,
  arrayContains,
  arrayPosition,
  arraySlice,
  arrayJoin,
  arrayAppend,
  arrayPrepend,
  arrayConcat,
  arrayDistinct,
  coalesce,
  nullIf,
  isNull,
  isNotNull,
  asc,
  desc,
  sumOver,
  cast,
  toInt,
  toFloat,
  toDate,
  round,
  array,
  fn,
  windowFn,
  when,
  shape,
  f,
  lit,
  currentDate,
  currentTimestamp,
  dateLiteral,
  timestampLiteral,
} from "./src/edsl/expr";

/** Language specification and dialect mapping helpers. */
export { LANGUAGE_SPEC, getLanguageSpec } from "./src/edsl/sql/language";
export type { LanguageCategory } from "./src/edsl/sql/language";

/** Dev utilities for source-watch SQL generation and clipboard copy. */
export {
  copyTextToClipboard,
  renderSqlFromSource,
  watchQuerySourceToClipboard,
} from "./src/edsl/dev";
export type {
  ClipboardTool,
  QueryLike,
  WatchQueryController,
  WatchQuerySourceOptions,
} from "./src/edsl/dev";

/** Common SQL type aliases and SQL rendering options. */
export type {
  BuiltinDialect,
  DialectLanguageConfig,
  DialectLanguageFallback,
  DialectFeatures,
  DialectSpec,
  QueryDialect,
  SqlInt,
  SqlFloat,
  SqlNumber,
  SqlDate,
  SqlTimestamp,
  Dialect,
  SqlFormat,
  SqlOptions,
} from "./src/edsl/types";
