/**
 * Query builders, relational operators, join helpers, projection helpers, and query rendering APIs.
 *
 * Import from this entrypoint when you need query composition without the full root API.
 *
 * @module
 */
export type {
  JoinKind,
  JoinOptions,
  JoinRightInput,
  Query,
  QueryColumns,
  QueryExplainResult,
  QueryIR,
  QueryStageKind,
  QueryStep,
  SqlRenderable,
  TakeWithinSpec,
  UnnestOptions,
  UnnestSelection,
} from "./mod.ts";

export {
  drop,
  dropOverlapLeft,
  dropOverlapRight,
  explain,
  extend,
  filter,
  filterEq,
  filterGt,
  filterGte,
  filterLt,
  filterLte,
  filterNe,
  fold,
  fullJoin,
  fullJoinMap,
  fullJoinMerge,
  identityStep,
  innerJoin,
  innerJoinMap,
  innerJoinMerge,
  isQuery,
  join,
  leftJoin,
  leftJoinMap,
  leftJoinMerge,
  loop,
  map,
  onEq,
  pick,
  prefixAllLeft,
  prefixAllRight,
  prefixOverlapLeft,
  prefixOverlapRight,
  rename,
  rightJoin,
  rightJoinMap,
  rightJoinMerge,
  sort,
  suffixAllLeft,
  suffixAllRight,
  t,
  table,
  take,
  takeWithin,
  toAst,
  toIR,
  toSql,
  toSqlResult,
  union,
  unionAll,
  unlessStep,
  unnest,
  usingCols,
  values,
  whenStep,
} from "./mod.ts";
