/** Alias used internally to bind correlated outer-query references. */
export const OUTER_TABLE_ALIAS = "__teta_outer__";
/** Prefix for generated scope identifiers. */
export const INTERNAL_SCOPE_PREFIX = "__teta_scope_";
/** Prefix for internal CTE names. */
export const INTERNAL_CTE_PREFIX = "__teta_cte_";
/** Current version of the public, cross-language query IR contract. */
export const TETA_QUERY_IR_VERSION = 1 as const;
/** Version accepted by the public query IR decoder. */
export type TetaQueryIrVersion = typeof TETA_QUERY_IR_VERSION;

/** Branded identifier for a query scope. */
export type ScopeId = string & { readonly __brand: "TetaScopeId" };
/** Branded CTE name generated for internal recursive queries. */
export type InternalCteName = string & { readonly __brand: "TetaInternalCteName" };
/** Branded CTE name generated by renderer planning. */
export type GeneratedCteName = string & { readonly __brand: "TetaGeneratedCteName" };

/** Return true when a string is an internal scope identifier. */
export function isInternalScopeName(value: string | null): value is ScopeId {
  return value !== null && value.startsWith(INTERNAL_SCOPE_PREFIX);
}

/** Return true when a string is an internal CTE name. */
export function isInternalCteName(value: string | null): value is InternalCteName {
  return value !== null && value.startsWith(INTERNAL_CTE_PREFIX);
}

/** Extract the human-readable label from an internal CTE name. */
export function internalCteLabel(value: string): string | null {
  if (!isInternalCteName(value)) return null;
  const remainder = value.slice(INTERNAL_CTE_PREFIX.length);
  const separatorIndex = remainder.indexOf("_");
  return separatorIndex >= 0 ? remainder.slice(0, separatorIndex) : remainder;
}

/** Build a stable generated CTE name from a prefix, label, and index. */
export function generatedCteName(
  prefix: string,
  label: string,
  index: number
): GeneratedCteName {
  return `${prefix}${label}_${index}` as GeneratedCteName;
}
