export type {
  ColumnRef,
  ExprRef,
  WindowBuilder,
} from "./expr/core.ts";

export {
  lit,
  param,
  array,
  fn,
  windowFn,
  wrapExpr,
  aggregateExpr,
  windowExpr,
  binaryExpr,
  funcExpr,
  over,
  containsGroup,
  dedupeExprs,
  shouldAlias,
  unwrapGroupExpr,
  toExprNode,
  isExprNode,
  toExprNodeList,
  toOrderItems,
  exprOf,
  columnOf,
  windowBuilderOf,
  isExpr,
  isColumn,
  type ColumnRefs,
  type Expr,
  type ExprLike,
  type ExprInput,
  type ExprInputTuple,
  type ExprInputValue,
  type ExprRefs,
  type NonNull,
  type PropagateNull,
  type ProjectionResult,
  type ProjectionSelection,
  type ProjectionShape,
  type ProjectionValue,
  type ProjectionValueResult,
  type Column,
  type WindowSpecInput,
  type WindowExpr,
} from "./expr/core.ts";
export { createColumnRefs, mergeColumnRefs, mergeColumnNames, projectAllItems } from "./expr/columns.ts";
