import {
  abs,
  add,
  cast,
  ceil,
  div,
  floor,
  greatest,
  least,
  mod,
  mul,
  pow,
  round,
  sqrt,
  sub,
  toFloat,
  toInt,
} from "../ops/math";
import { toDate } from "../ops/date";
import { defineExprMethods } from "./shared";

defineExprMethods([
  ["add", add],
  ["sub", sub],
  ["mul", mul],
  ["div", div],
  ["mod", mod],
  ["ceil", ceil],
  ["floor", floor],
  ["abs", abs],
  ["sqrt", sqrt],
  ["pow", pow],
  ["greatest", greatest],
  ["least", least],
  ["cast", cast],
  ["toInt", toInt],
  ["toFloat", toFloat],
  ["toDate", toDate],
  ["round", round],
]);
