import {
  bitLength,
  charLength,
  characterLength,
  concat,
  left,
  lower,
  lpad,
  octetLength,
  overlay,
  position,
  regexExtract,
  regexLike,
  regexReplace,
  replace,
  reverse,
  right,
  rpad,
  substring,
  trim,
  upper,
} from "../ops/string.ts";
import { defineExprMethods } from "./shared.ts";

defineExprMethods([
  ["replace", replace],
  ["upper", upper],
  ["lower", lower],
  ["reverse", reverse],
  ["trim", trim],
  ["regexLike", regexLike],
  ["regexReplace", regexReplace],
  ["regexExtract", regexExtract],
  ["substring", substring],
  ["position", position],
  ["overlay", overlay],
  ["charLength", charLength],
  ["characterLength", characterLength],
  ["octetLength", octetLength],
  ["bitLength", bitLength],
  ["left", left],
  ["right", right],
  ["lpad", lpad],
  ["rpad", rpad],
  ["concat", concat],
]);
