export const LANGUAGE_SPEC = {
  math: [
    "+",
    "-",
    "*",
    "/",
    "MOD",
    "ABS",
    "CEIL",
    "FLOOR",
    "SQRT",
    "ROUND",
    "POWER",
    "GREATEST",
    "LEAST",
  ],
  string: [
    "CONCAT",
    "UPPER",
    "LOWER",
    "TRIM",
    "SUBSTRING",
    "POSITION",
    "OVERLAY",
    "CHAR_LENGTH",
    "CHARACTER_LENGTH",
    "OCTET_LENGTH",
    "BIT_LENGTH",
    "REPLACE",
    "REVERSE",
    "LEFT",
    "RIGHT",
    "LPAD",
    "RPAD",
    "REGEXP_LIKE",
    "REGEXP_REPLACE",
    "REGEXP_EXTRACT",
  ],
  logical: [
    "=",
    "!=",
    "<",
    "<=",
    ">",
    ">=",
    "AND",
    "OR",
    "NOT",
    "LIKE",
    "IN",
  ],
  dateTime: [
    "CURRENT_DATE",
    "CURRENT_TIMESTAMP",
    "EXTRACT",
    "DATE_TRUNC",
    "DATE_ADD",
    "DATE_DIFF",
    "DATE_PARSE",
    "DATE_FORMAT",
    "TO_UNIXTIME",
    "FROM_UNIXTIME",
  ],
  conversionAndNull: [
    "CAST",
    "TRY_CAST",
    "COALESCE",
    "NULLIF",
    "IS NULL",
    "IS NOT NULL",
  ],
  array: [
    "ARRAY_LENGTH",
    "ARRAY_CONTAINS",
    "ARRAY_POSITION",
    "ARRAY_SLICE",
    "ARRAY_JOIN",
    "ARRAY_APPEND",
    "ARRAY_PREPEND",
    "ARRAY_CONCAT",
    "ARRAY_DISTINCT",
  ],
  windowAndAgg: [
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "RANK",
    "DENSE_RANK",
    "ROW_NUMBER",
    "LAG",
    "LEAD",
    "PERCENT_RANK",
    "NTILE",
  ],
  queryFeatures: ["LATERAL_JOIN", "RECURSIVE_CTE"],
} as const;

export type LanguageCategory = keyof typeof LANGUAGE_SPEC;

export function getLanguageSpec(): typeof LANGUAGE_SPEC {
  return LANGUAGE_SPEC;
}
